### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by djh0ffman** [djh0ffman/ProTrackerTools#1]
- [x] Function to zero first 2 bytes of each one hit sample
- [ ] Search and replace function, including complex eval
- [ ] Swap sample function
- [x] Truncate loop function, remove all sample data outside the loop
- [ ] Make serializer static
- [x] Fixed width font for sample names
- [x] Import ASCII
- [ ] Command line version
